---
title: "Create a Summary of the contents of each COMLAND table"
author: "Alex Hanke"
date: "April 20, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load some packages

```{r cars}
library(RODBC)
require(plyr)
memory.limit(size=4095)

channel <- odbcConnect("ptran", uid="hankea", pwd="StAndr3ws",believeNRows=F)
```
Create a list of all possible tables within COMLAND
```{r cars}
Tables = sqlTables(channel,schema="COMLAND")$TABLE_NAME
TableName = c('CATCHERS_1967','CATCHERS_2003','CL_LOG_HEADER_1967','CL_LOG_HEADER_2003','C_1986_2001','IDENTIFIED_CATCHES_1967','IDENTIFIED_CATCHES_2003','I_1986_2001','NAFO_AREA_CODES','NAFO_AREA_CODES_WITH_XY','NAFO_CATCH','NAFO_CODES','NAFO_COUNTRY_CODES','NAFO_EFFORT','NAFO_GEAR_CODES','NAFO_MAIN_SPECIES_CODES','NAFO_SPECIES_CODES','NAFO_SUMMARY','NAFO_TONNAGE_CLASS_CODES','SPECIES_CODE_LINK','SUB_TRIPS_1967','SUB_TRIPS_2003','S_1986_2001','AUXILIARY_EQUIPMENTS','CATCHERS_1986_2001','COMMUNITIES','CONVERSIONS','DFO_REGIONS','ELECTORAL_DISTRICTS','FORMS','GEARS','GEAR_CATEGORIES','GEAR_CLASSES','GEAR_TYPES','GEAR_TYPES_PRE_1986','HORSEPOWER_CLASSES','IDENTIFIED_CATCHES_1986_2001','LOBSTER_DISTRICTS','NAFO_CATCH_EFFORT','NAFO_DIVISIONS','NAFO_SUB_AREAS','NAFO_YEARS','PROVINCES','QUALITIES','QUOTAS','SIZES','SPECIES','SPECIES_CLASSES','SPECIES_PRE_1986','STATISTICAL_DISTRICTS','STOCKS','STOCK_AREAS','SUB_TRIPS_1986_2001','TONNAGE_CLASSES','TONNAGE_CLASSES_PRE_1986','TRIP_AUX_EQPT','UNITS_OF_MEASURE')
# catenate schema and name
TableName = paste("COMLAND",TableName,sep=".")
```

Open and close each table in turn.
```{r , echo=FALSE}
if(exists("Table_desc")){rm(Table_desc)}
# Create a list of MARFIS tables where eac table has 4 rows  
for(i in TableName){
  if(!exists("Table_desc")){ Table_desc = 
  list(t(sqlQuery(channel, paste("select * from ",
                        i,
                        " where rownum<5"))))
  names(Table_desc)=get("i")}
  
  temp = list(t(sqlQuery(channel, paste("select * from ",
                        i,
                        " where rownum<5"))))
  names(temp)=get("i")
  Table_desc = c(Table_desc,temp)
}

# rename the elements of the list
names(Table_desc) = unlist(lapply(strsplit(names(Table_desc),"[.]"),function(x) x[2]))
```
Save to file. First we need to process the list so that each element is a dataframe and we should identify the table name before binding it all together.
```{r}
# Not all tables are populated so we need to remove any that are empty otherwise the next part will crash. Also I don't have permission to view all tables so I need to remove those as well.
valid = unlist(lapply(Table_desc,function(x) dim(x)[2]))>0
valid = valid & unlist(lapply(Table_desc,function(x) substring(x[1],1,5)!="HY000"))
names(Table_desc)[valid]

for(i in (1:length(Table_desc))[valid] ){
  temp = as.data.frame(Table_desc[[i]])
  temp = cbind(data.frame(Name=rownames(temp)),temp)
  nodata <- as.data.frame(setNames(replicate(5,numeric(0), simplify = F), letters[1:5]))
  names(nodata) = names(temp)
  nodata[1,] = c(names(Table_desc[i]),rep("",4))
  temp = rbind.fill(nodata,temp)
    if(i==1){
      Table_desc2 = temp
    }else{Table_desc2 = rbind.fill(Table_desc2,temp)
    }
  }

write.csv(Table_desc2, file="COMLAND_tables_summary.csv")
```

