---
title: "A summary of the CL tables"
author: "Alex Hanke"
date: "May 5, 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load some packages

```{r cars}
library(RODBC)
require(plyr)
memory.limit(size=4095)

channel <- odbcConnect("ptran", uid="hankea", pwd="StAndr3ws",believeNRows=F)
```
Create a list of all possible tables within COMLAND
```{r cars}
Tables = sqlTables(channel,schema="CL")$TABLE_NAME
TableName = c('AUXILIARY_EQUIPMENTS','CATCHERS','CATCHERS_1986','CATCHERS_2003','CATCHER_TYPES','COMMUNITIES','COMPANIES','CONVERSIONS','DEPTHS','DFO_REGIONS','ELECTORAL_DISTRICTS','FORMS','GEARS','GEAR_CATEGORIES','GEAR_CLASSES','GEAR_TYPES','GEAR_TYPES_PRE_1986','HORSEPOWER_CLASSES','HULL_TYPES','IDCATYYYY','IDENTIFIED_CATCHES_1986','IDENTIFIED_CATCHES_2003','INFO_TRANSFERT','LENGTH_CLASSES','LOADCOMMUNITIES','LOADCOMPANIES','LOG_DETAIL_1995','LOG_DETAIL_2003','LOG_ESTIMATE_1995','LOG_ESTIMATE_2003','LOG_HEADER_1995','LOG_HEADER_2003','NAFO_DIVISIONS','NAFO_SUB_AREAS','NAFO_UNIT_AREAS','OLD_IDENTIFIED_CATCHES_1999','OLD_SUB_TRIPS_1999','OLD_TRIPS_1999','PROVINCES','QUALITIES','QUOTAS','SIZES','SLIP_DETAIL_1995','SLIP_HEADER_2003','SPECIES','SPECIES_CLASSES','SPECIES_INCLUDED','SPECIES_PRE_1986','STATISTICAL_DISTRICTS','STIDYYYY','STOCKS','STOCK_AREAS','STYYYY','SUB_TRIPS_1986','SUB_TRIPS_2003','SUMMARIZED_CATCHES','SUMMARIZED_EFFORTS','SV_TRANSFERE','TEMP2009','TEMPGULF','TEMPMAR','TEMPMAR1213','TEMPMAR2009','TEMPNFLD','TEMPQUE','TEST','TEST_LOG_HEADER','TONNAGE_CLASSES','TONNAGE_CLASSES_PRE_1986','TONNAGE_CLASSES_X','TRIPS_1986','TRIPS_2003','TRIP_AUX_EQPT','TRIP_SUB_TRIP_FLAGS','UNITS_OF_MEASURE','VOYAGE_PRESENT','ZIFDB','ZIFDB19862008','ZIFNEW1986','ZIFNEW2008','ZIFNHQ1986','ZIFNHQ2002','ZIFYYYY','ZN2006','ALL_CATCHERS_VIEW','ALL_IDENTIFIED_CATCHES_VIEW','ALL_SUB_TRIPS_VIEW','ALL_TRIPS_VIEW','SPECIESTESTVIEW','YEARS_OF_ACTIVITY')
# catenate schema and name
TableName = paste("CL",TableName,sep=".")
```

Open and close each table in turn.
```{r , echo=FALSE}
if(exists("Table_desc")){rm(Table_desc)}
# Create a list of MARFIS tables where eac table has 4 rows  
for(i in TableName){
  if(!exists("Table_desc")){ Table_desc = 
  list(t(sqlQuery(channel, paste("select * from ",
                        i,
                        " where rownum<5"))))
  names(Table_desc)=get("i")}
  
  temp = list(t(sqlQuery(channel, paste("select * from ",
                        i,
                        " where rownum<5"))))
  names(temp)=get("i")
  Table_desc = c(Table_desc,temp)
}

# rename the elements of the list
names(Table_desc) = unlist(lapply(strsplit(names(Table_desc),"[.]"),function(x) x[2]))
```
Save to file. First we need to process the list so that each element is a dataframe and we should identify the table name before binding it all together.
```{r}
# Not all tables are populated so we need to remove any that are empty otherwise the next part will crash. Also I don't have permission to view all tables so I need to remove those as well.
valid = unlist(lapply(Table_desc,function(x) dim(x)[2]))>0
valid = valid & unlist(lapply(Table_desc,function(x) substring(x[1],1,5)!="HY000"))
names(Table_desc)[valid]

for(i in (1:length(Table_desc))[valid] ){
  j = (1:length(Table_desc))[valid][1]
  temp = as.data.frame(Table_desc[[i]])
  temp = cbind(data.frame(Name=rownames(temp)),temp)
  nodata <- as.data.frame(setNames(replicate(5,numeric(0), simplify = F), letters[1:5]))
  names(nodata) = names(temp)
  nodata[1,] = c(names(Table_desc[i]),rep("",4))
  temp = rbind.fill(nodata[,1:3],temp)
    if(i==j){
      Table_desc2 = temp
    }else{Table_desc2 = rbind.fill(Table_desc2,temp)
    }
  }

write.csv(Table_desc2, file="CL_tables_summary.csv")
```

